export { default as Response } from './core/response';
export { default as Road } from './core/road';
export { default as RoadsPJAX } from './client/pjax';
export { default as Request } from './client/request';
export { default as build } from './client/build';
import applyToContext from './middleware/applyToContext';
import cors from './middleware/cors';
import reroute from './middleware/reroute';
import SimpleRouter from './middleware/simpleRouter';
declare const Middleware: {
    applyToContext: typeof applyToContext;
    cookie: import("./core/road").Middleware;
    cors: typeof cors;
    killSlash: import("./core/road").Middleware;
    parseBody: import("./core/road").Middleware;
    reroute: typeof reroute;
    setTitle: import("./core/road").Middleware;
    SimpleRouter: typeof SimpleRouter;
};
export { Middleware };
