name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # 8.x and lower not supported due to lack of URL object
        # 10.x not supported with the current version of EJS. If you need it, it will probably run fine
        # 14.x and 15.x are not supported by vitest
        # 19.x and up the request UA is `undici` and affected the tests
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true
